branch-defaults:
  resorts:
    environment: null
    group_suffix: null
environment-defaults:
  skiApp-backend-dev:
    branch: null
    repository: null
global:
  application_name: skiApp_backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.6 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
